name: zap
on: workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'https://dev-biohubbc.apps.silver.devops.gov.bc.ca/'
